[package]
name = "use-date-range"
description = "Primitive date-range helpers"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/use-date-range"
keywords = ["calendar", "date", "range"]
categories = ["algorithms", "science"]

[dependencies]
use-date.workspace = true

[lints]
workspace = true